services:
  aspen:
    image: ghcr.io/nielsmaerten/aspen:latest
    env_file:
      - .env
    environment:
      - ASPEN_WATCH=1
      - ASPEN_LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
      - ./prompts:/app/prompts
    restart: unless-stopped
